# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ab_tester}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dalton Pinto"]
  s.date = %q{2011-06-01}
  s.description = %q{Yet another AB Test gem, but this supports AbstractController, not only ActionController}
  s.email = %q{dalthon@aluno.ita.br}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "ab_tester.gemspec",
    "lib/ab_choice.rb",
    "lib/ab_tester.rb",
    "lib/ab_tester/choice_options.rb",
    "lib/helpers/ab_choice_helper.rb",
    "lib/rails/generators/a_b_tester/a_b_tester_generator.rb",
    "lib/rails/generators/a_b_tester/templates/create_ab_choices.rb",
    "lib/tasks/ab_tester.rake",
    "test/helper.rb",
    "test/test_ab_tester.rb"
  ]
  s.homepage = %q{http://github.com/efqdalton/ab_tester}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A simple gem for AB Tests}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

